var verbs = {
    0:[['ser'],['to be']], 
    1:[['haber'],['to have']], 
    2:[['estar'],['to be']], 
    3:[['tener'],['to have']], 
    4:[['hacer'],['to do']], 
    5:[['poder'],['to be able']], 
    6:[['decir'],['to say']], 
    7:[['ir'],['to go']], 
    8:[['ver'],['to see']], 
    9:[['dar'],['to give']], 
    10:[['saber'],['to know']], 
    11:[['querer'],['to want']], 
    12:[['llegar'],['to arrive']], 
    13:[['pasar'],['to pass']], 
    14:[['deber'],['to owe']], 
    15:[['poner'],['to put']], 
    16:[['parecer'],['to seem']], 
    17:[['quedar'],['to stay']], 
    18:[['creer'],['to believe']], 
    19:[['hablar'],['to speak']], 
    20:[['llevar'],['to carry']], 
    21:[['dejar'],['to leave']], 
    22:[['seguir'],['to follow']], 
    23:[['encontrar'],['to find']], 
    24:[['llamar'],['to call']]
}