var verbs = {
    0:[['ser'],['to be']], 
    1:[['tener','haber'],['to have']], 
    2:[['estar'],['to be']], 
    3:[['venir'],['to come']], 
    4:[['hacer'],['to do','make']], 
    5:[['poder'],['to be able','can']], 
    6:[['decir'],['to say','tell']], 
    7:[['ir'],['to go']], 
    8:[['ver'],['to see']], 
    9:[['dar'],['to give']], 
    10:[['saber'],['to know']], 
    11:[['querer'],['to want','love']], 
    12:[['llegar'],['to arrive','come','reach']], 
    13:[['pasar'],['to pass','to spend','to happen']], 
    14:[['deber'],['to owe','must','should','ought to']], 
    15:[['poner'],['to put','place','set']], 
    16:[['parecer'],['to seem','appear']], 
    17:[['quedar'],['to stay','remain']], 
    18:[['creer'],['to believe']], 
    19:[['hablar'],['to speak']], 
    20:[['llevar'],['to carry','bring']], 
    21:[['dejar'],['to leave','abandon','to let','allow']], 
    22:[['seguir'],['to follow','continue']], 
    23:[['encontrar'],['to find','encounter']], 
    24:[['llamar'],['to call','to name']]
}