var verbs = {
    0:[['ser','estar'],['to be']], 
    1:[['tener','haber'],['to have']], 
    2:[['pensar'],['to think']], 
    3:[['venir'],['to come']], 
    4:[['hacer'],['to do','to make']], 
    5:[['poder'],['to be able','can']], 
    6:[['decir'],['to say','to tell']], 
    7:[['ir'],['to go']], 
    8:[['ver'],['to see']], 
    9:[['dar'],['to give']], 
    10:[['saber'],['to know']], 
    11:[['querer'],['to want','to love']], 
    12:[['llegar'],['to arrive','to come','to reach']], 
    13:[['pasar'],['to pass','to spend','to happen']], 
    14:[['deber'],['to owe','must','should','ought to']], 
    15:[['poner'],['to put','to place','to set']], 
    16:[['parecer'],['to seem','to appear']], 
    17:[['quedar'],['to stay','to remain']], 
    18:[['creer'],['to believe']], 
    19:[['hablar'],['to speak']], 
    20:[['llevar'],['to carry','to bring']], 
    21:[['dejar'],['to leave','to abandon','to let','to allow']], 
    22:[['seguir'],['to follow','to continue']], 
    23:[['encontrar'],['to find','to encounter']], 
    24:[['llamar'],['to call','to name']],
    25:[['llegar'],['to arrive','to reach']]
}